name: active-dynamics
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - ipykernel
  - ipython
  - matplotlib
  - numpy
  - scipy
  - scikit-learn
  - tqdm
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::cpuonly
  - gymnasium
  - gym
  - colorednoise
  - pyyaml
  - tensordict
  - pip:
    - contourpy==1.3.1
    - cycler==0.12.1
    - fonttools==4.55.2
    - joblib==1.4.2
    - kiwisolver==1.4.7
    - pillow==11.0.0
    - pyparsing==3.2.0
    - threadpoolctl==3.5.0
