"""Matplotlib style helpers shared across experiments.

Style application comes in two forms: the legacy global mutators
(:func:`set_matplotlib_style`, :func:`apply_manuscript_figure_style`) and the
scoped :func:`manuscript_rc` context manager. New code should prefer the
context manager so figures generated by different experiments in one process
cannot leak rcParams into each other.
"""

from __future__ import annotations

import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from cycler import cycler
from matplotlib.colors import LogNorm


def set_matplotlib_style():
    plt.rcParams.update(
        {
            "font.family": "helvetica",
            "font.size": 14.0,
            "lines.linewidth": 2,
            "lines.antialiased": True,
            "axes.prop_cycle": cycler(color=sns.color_palette("husl", 8)),
            "axes.facecolor": "fdfdfd",
            "axes.edgecolor": "777777",
            "axes.linewidth": 1,
            "axes.titlesize": "medium",
            "axes.labelsize": "medium",
            "axes.axisbelow": True,
            "xtick.major.size": 0,  # major tick size in points
            "xtick.minor.size": 0,  # minor tick size in points
            "xtick.major.pad": 6,  # distance to major tick label in points
            "xtick.minor.pad": 6,  # distance to the minor tick label in points
            "xtick.color": "333333",  # color of the tick labels
            "xtick.labelsize": "medium",  # fontsize of the tick labels
            "xtick.direction": "in",  # direction: in or out
            "ytick.major.size": 0,  # major tick size in points
            "ytick.minor.size": 0,  # minor tick size in points
            "ytick.major.pad": 6,  # distance to major tick label in points
            "ytick.minor.pad": 6,  # distance to the minor tick label in points
            "ytick.color": "333333",  # color of the tick labels
            "ytick.labelsize": "medium",  # fontsize of the tick labels
            "ytick.direction": "in",  # direction: in or out
            "axes.grid": True,
            "grid.alpha": 0.3,
            "grid.linewidth": 1,
            "legend.fancybox": True,
            "legend.fontsize": "Small",
            "figure.facecolor": "1.0",
            "figure.edgecolor": "0.5",
            "hatch.linewidth": 0.1,
            "text.usetex": True,
        }
    )


def manuscript_rc_params(
    *,
    font_size: float = 7.8,
    stroke_color: str = "#3A3A3A",
) -> dict:
    """Compact manuscript figure defaults used by experiment summaries."""
    return {
        "text.usetex": False,
        "font.family": "serif",
        "font.serif": ["Computer Modern Roman", "CMU Serif", "DejaVu Serif"],
        "font.size": float(font_size),
        "figure.dpi": 300,
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
        "axes.edgecolor": stroke_color,
        "axes.linewidth": 0.55,
        "axes.labelcolor": stroke_color,
        "xtick.color": stroke_color,
        "ytick.color": stroke_color,
        "xtick.major.width": 0.45,
        "ytick.major.width": 0.45,
        "xtick.major.size": 2.0,
        "ytick.major.size": 2.0,
        "legend.frameon": False,
        "savefig.bbox": "tight",
        "savefig.pad_inches": 0.02,
    }


def apply_manuscript_figure_style(
    plt_module=plt,
    *,
    font_size: float = 7.8,
    stroke_color: str = "#3A3A3A",
) -> None:
    """Apply compact manuscript figure defaults used by experiment summaries."""
    plt_module.rcParams.update(
        manuscript_rc_params(font_size=font_size, stroke_color=stroke_color)
    )


def manuscript_rc(
    extra: dict | None = None,
    *,
    font_size: float = 7.8,
    stroke_color: str = "#3A3A3A",
):
    """Scoped manuscript style: use as ``with manuscript_rc(): ...``."""
    params = manuscript_rc_params(font_size=font_size, stroke_color=stroke_color)
    if extra:
        params.update(extra)
    return matplotlib.rc_context(params)


def style_manuscript_axis(
    ax,
    *,
    grid_axis: str | None = None,
    grid_color: str = "#C8C1B8",
    grid_alpha: float = 0.42,
    stroke_color: str = "#3A3A3A",
    grid_linewidth: float = 0.35,
    spine_linewidth: float = 0.55,
) -> None:
    """Apply compact axis styling for manuscript summary figures."""
    if grid_axis is None:
        ax.grid(color=grid_color, linewidth=grid_linewidth, alpha=grid_alpha)
    else:
        ax.grid(axis=grid_axis, color=grid_color, linewidth=grid_linewidth, alpha=grid_alpha)
    for spine in ax.spines.values():
        spine.set_color(stroke_color)
        spine.set_linewidth(spine_linewidth)
    ax.tick_params(width=0.45, length=2.0, colors=stroke_color)


def decorate_phase_space_axis(
    ax,
    *,
    xlim: tuple[float, float],
    ylim: tuple[float, float],
    title: str,
    xlabel: str = "x",
    ylabel: str = "v",
    legend_loc: str = "upper right",
    grid_alpha: float = 0.25,
) -> None:
    ax.set_xlim(*xlim)
    ax.set_ylim(*ylim)
    ax.set_aspect("equal", adjustable="box")
    ax.grid(alpha=grid_alpha)
    ax.set_xlabel(xlabel)
    ax.set_ylabel(ylabel)
    ax.set_title(title)
    handles, labels = ax.get_legend_handles_labels()
    if handles:
        ax.legend(loc=legend_loc)


def make_lognorm(values: list[np.ndarray]) -> LogNorm:
    flat = np.concatenate([np.ravel(np.asarray(value, dtype=float)) for value in values], axis=0)
    positive = flat[np.isfinite(flat) & (flat > 0)]
    if positive.size == 0:
        return LogNorm(vmin=1e-8, vmax=1.0)
    min_positive = float(np.min(positive))
    p1 = float(np.percentile(positive, 1.0))
    p99 = float(np.percentile(positive, 99.0))
    vmin = max(min_positive, p1)
    vmax = max(p99, vmin * 1.01)
    return LogNorm(vmin=vmin, vmax=vmax)
